### ISSUE TITLE
Missing scores for comparison

### ISSUE THREAD

**Issue by Keith-Hon** [neonbjb/tts-scores#3]
The scores are missing from "Scores from common models" section

**Comment by neonbjb** [comment]
Yeah... I didn't do this. I started down the path and quickly got disheartened in figuring out that most models were not really OSS, basically it's just tacotron, and everything else is just reproductions that "mostly work".

**Comment by Keith-Hon** [comment]
> Yeah... I didn't do this. I started down the path and quickly got disheartened in figuring out that most models were not really OSS, basically it's just tacotron, and everything else is just reproductions that "mostly work".

I see... thank you for open sourcing this :)
