### ISSUE TITLE
.data/clvp.pth is missing

### ISSUE THREAD

**Issue by tatujan** [neonbjb/tts-scores#4]
Looks like the CLVP pretrained model is missing. I've found two models on your HuggingFace repo namely,`clvp.pth` and `clvp2.pth` but it seems incompatible. There were bunch of param size mismatches and missing keys in `state_dict for CLVP` when testing with tts-score to compute Frechet Distance. How can I get around this issue?

**Comment by tatujan** [comment]
Nevermind, I was looking at the wrong repo (tortoise's). Here is the link to the right clvp.pth on HugginFace [https://huggingface.co/jbetker/tts-scores-clvp/tree/main](url) if anyone has the same issue.

**Comment by CamellIyquitous** [comment]
Thank you very much!
