### ISSUE TITLE
Realism

### ISSUE THREAD

**Issue by fakerybakery** [neonbjb/tts-scores#8]
Hi,
Does this repo also evaluate how realistic the voices are?

**Comment by neonbjb** [comment]
Nope; any ideas for how such an eval would work?

**Comment by fakerybakery** [comment]
Hmm, I don't know how that would work. Thanks though!

**Comment by fakerybakery** [comment]
One thing - so with this eval, running it on samples generated by a non-AI TTS system (ie espeak, macOS "say" command, festival, etc) would give similar results to running it on samples generated by Tortoise/XTTS?
